act_type: gelu
all_qp: true
av1: true
batch_size: 8
c_plainsr: 32
colors: 3
comment: Val_BEST
config: configs/l2_finetune_best_model_repv12.yml
data_augment: 1
data_path: ../datasets/
data_repeat: 20
decays:
- 200
- 400
- 600
epochs: 800
gamma: 0.5
gpu_ids: 0
log_every: 100
log_name: null
log_path: ./experiments/l1_dist_1_combined_qp_all
loss: l2
lr: 5.0e-05
m_plainsr: 1
min_lr: 1.0e-06
mixed_pred: true
model: RepNetwork_V012_BestStruct
normalize: true
num_workers: 8
optimizer: adam
patch_size: 384
pretrain: ./checkpoint/Best_model_DIV2K_qp_all/models/model_x4_best.pt
qp_value: 31
resume: null
save_val_image: false
scale: 4
scheduler: CosineAnnealingWarmRestarts
test_every: 1
test_path: ../datasets/RTSR/val_lr
train_set: Combined4
val_set: DIV2K
wandb: false
wd: 0.0
with_bn: 0
