act_type: gelu
av1: true
batch_size: 8
c_plainsr: 32
colors: 3
comment: Val_BEST
config: ./configs/best_model_repv12.yml
data_augment: 1
data_path: ../datasets/AIS2024/
data_repeat: 20
decays:
- 200
- 400
- 600
epochs: 800
gamma: 0.5
gpu_ids: 2
log_every: 100
log_name: null
log_path: ./experiments
loss: l1
lr: 0.0005
m_plainsr: 1
min_lr: 1.0e-06
mixed_pred: true
model: RepNetwork_V012_BestStruct
normalize: true
num_workers: 8
optimizer: adam
patch_size: 384
pretrain: null
qp_value: 31
resume: null
save_val_image: false
scale: 4
scheduler: CosineAnnealingWarmRestarts
test_every: 1
test_path: ../datasets/AIS2024/val_phase/
train_set: DIV2K
val_set: DIV2K
wandb: false
wd: 0.0
with_bn: 0
