model: 'DownRepConv_v2'
comment: 'Val_BEST'
## parameters for plain
scale: 4
colors: 3
m_plainsr: 1
c_plainsr: 32
with_bn: 0
act_type: 'gelu'
pretrain:

## loss function & optimizer
loss: 'l1'

## optimizer:
optimizer: adam
lr: 0.0005

## scheduler:
scheduler: 'CosineAnnealingWarmRestarts'
decays: [200, 400, 600]
gamma: 0.5
wd: 0.0
min_lr: 0.000001

## parameters for model training
epochs: 800

patch_size: 384
batch_size: 8
data_repeat: 20
data_augment: 1

log_every: 100
test_every: 1
log_path: "./experiments"
log_name:
save_val_image: False

wandb: False

## Fp16 training
mixed_pred: True
normalize: True

## hardware specification
threads: 1

## data specification
data_path: '../datasets/'
test_path: '../datasets/RTSR/val_lr'
eval_sets: ['DIV2K']

av1 : True
qp_value : 31