model: 'bicubic_plus_plus'
comment: 'Val_BEST'
## parameters for plain
scale: 4
colors: 3
m_plainsr: 1
c_plainsr: 32
with_bn: 0
act_type: 'gelu'
pretrain:

## loss function & optimizer
loss: 'l2'

## optimizer:
optimizer: adam
lr: 0.00005

## scheduler:
scheduler: 'CosineAnnealingWarmRestarts'
decays: [200, 400, 600]
gamma: 0.5
wd: 0.0
min_lr: 0.000001

## parameters for model training
epochs: 1000

patch_size: 384
batch_size: 16
data_repeat: 1
data_augment: 1

log_every: 100
test_every: 1
log_path: "./experiments"
log_name:
save_val_image: True

wandb: False

## Fp16 training
mixed_pred: True
normalize: True

## hardware specification
num_workers: 8

## data specification
# data_path: '../datasets/AIS2024/'
# test_path: '../datasets/AIS2024/val_phase/'
data_path: '/dataset/SR/AIS2024/'
test_path: '/dataset/SR/AIS2024/val_phase/'
val_set: 'DIV2K'
train_set: 'DIV2K'

av1 : True
qp_value : 31
all_qp: False
a_aug: False
distillation: False