a_aug: false
act_type: gelu
all_qp: true
av1: true
batch_size: 8
c_plainsr: 32
colors: 3
comment: Val_BEST
config: ./configs/l2_finetune_best_model_repv12_adamw.yml
data_augment: 1
data_path: ../datasets/AIS2024/
data_repeat: 20
decays:
- 200
- 400
- 600
epochs: 800
gamma: 0.5
gpu_ids: 0
log_every: 100
log_name: null
log_path: ./experiments
loss: l2
lr: 5.0e-05
m_plainsr: 1
min_lr: 1.0e-08
mixed_pred: true
model: RepNetwork_V012_BestStruct
normalize: true
num_workers: 8
optimizer: adamw
patch_size: 384
pretrain: ./chekpoints/RepNetwork_V012_BestStruct_x4_p384_m1_c32_gelu_l1_adam_lr0.0005_e800_t2024-0320-0719/models/model_x4_best.pt
qp_value: 31
resume: null
save_val_image: false
scale: 4
scheduler: CosineAnnealingWarmRestarts
test_every: 1
test_path: ../datasets/AIS2024/val_phase/
train_set: DIV2K
val_set: DIV2K
wandb: false
wd: 0.0
with_bn: 0
